name: test first github action workflow
on: 
  push:
    branches: 
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: run first gh action
      run: echo "hello world"
    
